version: '3'
services:

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: nginx
    pgsql:
        image: postgres:13.3
        environment:
            - POSTGRES_DB=forumdb
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=111
        ports:
            - "5432:5432"
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        container_name: app
